package={name= 'kms', version= '0.0.0', edition= '2021'}
bin=[{name='kms',path= 'main.rs'}]

[build-dependencies]
bindgen='*'
cc={version='*', features=['parallel']}

[dependencies]
bytemuck='*'
drm-fourcc='*'
drm='*'
#ffmpeg ={package='ffmpeg-sys-next', version='*'}
