package={name= 'kms', version= '0.0.0', edition= '2021'}
bin=[{name='kms',path= 'main.rs'}]

[dependencies]
bytemuck='*'
drm='*'
ffmpeg ={package='ffmpeg-next', version='*'}
va={package='libva-sys',version='*'}

[patch.'crates-io']
drm={path='../drm-rs'}
libva-sys={git='https://github.com/vgarleanu/libva-sys', commit='f5d78be'}