package={name= 'kms', version= '0.0.0', edition= '2021'}
bin=[{name='kms',path= 'main.rs'}]

[build-dependencies]
bindgen = '*'

[dependencies]
itertools='*'
num-derive='*'
num-traits='*'
bytemuck='*'
nom='*'
memmap='*'
matroska={version='*', git='https://github.com/rust-av/matroska'}
dma-buf='*'
#drm='*'

[patch.'crates-io']
libva-sys={git='https://github.com/vgarleanu/libva-sys', commit='f5d78be'}
